// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kodama/protobuf/ping/ping.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	kodama/protobuf/ping/ping.proto

It has these top-level messages:
	Ping
	Pong
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ping struct {
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Pong struct {
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Ping)(nil), "kodama.protobuf.ping.Ping")
	proto.RegisterType((*Pong)(nil), "kodama.protobuf.ping.Pong")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PingService service

type PingServiceClient interface {
	Send(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type pingServiceClient struct {
	cc *grpc.ClientConn
}

func NewPingServiceClient(cc *grpc.ClientConn) PingServiceClient {
	return &pingServiceClient{cc}
}

func (c *pingServiceClient) Send(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := grpc.Invoke(ctx, "/kodama.protobuf.ping.PingService/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PingService service

type PingServiceServer interface {
	Send(context.Context, *Ping) (*Pong, error)
}

func RegisterPingServiceServer(s *grpc.Server, srv PingServiceServer) {
	s.RegisterService(&_PingService_serviceDesc, srv)
}

func _PingService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kodama.protobuf.ping.PingService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServiceServer).Send(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kodama.protobuf.ping.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _PingService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kodama/protobuf/ping/ping.proto",
}

func init() { proto.RegisterFile("kodama/protobuf/ping/ping.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0xce, 0x4f, 0x49,
	0xcc, 0x4d, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0xc8, 0xcc, 0x4b,
	0x07, 0x13, 0x7a, 0x60, 0x21, 0x21, 0x11, 0x88, 0x02, 0x3d, 0x98, 0x02, 0x3d, 0x90, 0x9c, 0x12,
	0x1b, 0x17, 0x4b, 0x00, 0x8c, 0xce, 0xcf, 0x4b, 0x37, 0xf2, 0xe5, 0xe2, 0x06, 0xf1, 0x83, 0x53,
	0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xec, 0xb8, 0x58, 0x82, 0x53, 0xf3, 0x52, 0x84, 0xa4, 0xf4,
	0xb0, 0xe9, 0xd6, 0x03, 0x29, 0x95, 0xc2, 0x25, 0x97, 0x9f, 0x97, 0xee, 0xa4, 0x1d, 0xa5, 0x99,
	0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9d, 0x58, 0x52, 0x9c, 0x5a,
	0xae, 0x8f, 0xdd, 0xa5, 0x49, 0x49, 0x6c, 0x60, 0x11, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc0, 0xc7, 0x50, 0x51, 0xcb, 0x00, 0x00, 0x00,
}
